// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtvPPhWZOH8JBk5s7ExNCGdnIQcld5fh0',
    appId: '1:602569029888:web:a177ae41032bd85678dbe5',
    messagingSenderId: '602569029888',
    projectId: 'tidymind-16438',
    authDomain: 'tidymind-16438.firebaseapp.com',
    storageBucket: 'tidymind-16438.firebasestorage.app',
    measurementId: 'G-M42HC29VLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCoQ2iulMivJH3o4uHUzIrAaDad9ZbmFw',
    appId: '1:602569029888:android:734a06d62c69e07778dbe5',
    messagingSenderId: '602569029888',
    projectId: 'tidymind-16438',
    storageBucket: 'tidymind-16438.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvvrPpfGmVMt6Ao83D6IdUutFZCTo0N8',
    appId: '1:602569029888:ios:d96a70ea3e15d4b178dbe5',
    messagingSenderId: '602569029888',
    projectId: 'tidymind-16438',
    storageBucket: 'tidymind-16438.firebasestorage.app',
    iosBundleId: 'edu.cpp.CS4740.example1.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvvrPpfGmVMt6Ao83D6IdUutFZCTo0N8',
    appId: '1:602569029888:ios:d96a70ea3e15d4b178dbe5',
    messagingSenderId: '602569029888',
    projectId: 'tidymind-16438',
    storageBucket: 'tidymind-16438.firebasestorage.app',
    iosBundleId: 'edu.cpp.CS4740.example1.test1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtvPPhWZOH8JBk5s7ExNCGdnIQcld5fh0',
    appId: '1:602569029888:web:3f80480c950ec6ef78dbe5',
    messagingSenderId: '602569029888',
    projectId: 'tidymind-16438',
    authDomain: 'tidymind-16438.firebaseapp.com',
    storageBucket: 'tidymind-16438.firebasestorage.app',
    measurementId: 'G-MKNBBKD57H',
  );

}